Часть повторяющегося кода вынесена в отд. файлы
VKNS/uber-copy-2 pull request #1
Opened 2018-07-06 11:28 UTC by VKNS

добавил js for-loops в блоки: clientAdv, driversReviews, newsBlock, uberfooter/components/doublingLinks/components/socialLinks.
Также в них часть повторяющегося кода была вынесена в отд. файлы.

несколько почистил css

2018-07-07 10:14 UTC, egorzalenski commented on app/components/clientAdv/index.js
> +import advText from './text/advantages.json';
переделай его в чистый массив объектов без ключей [{}, {}, {}] и в `render` сделай по нему `map`

2018-07-07 10:36 UTC, ghost requested changes
нужно переделать циклы

2018-07-07 10:36 UTC, egorzalenski commented on app/components/companyAdv/styles/companyAdv.css
> +  background: url(https://d1a3f4spazzrp4.cloudfront.net/chameleon-assets/v1.0.0/4878ffeb-2036-485f-b274-73f0f36e3a71/palm.jpg)
в одну строчку

2018-07-07 10:36 UTC, egorzalenski commented on app/components/driversReviews/index.js
> +let State = {};
тоже самое

2018-07-07 10:36 UTC, egorzalenski commented on app/components/driversReviews/styles/driversReviews.css
> +    padding: 40px 100px 40px 100px;
сделай паддинги в 2 аргумента

2018-07-07 10:36 UTC, egorzalenski commented on app/components/mainAd/components/driversRegistr/index.js
> +function createMarkup(val) {
вынеси эту функцию в какую-нибудь папку `util` и от туда везде импорти и испоьзуй

2018-07-07 10:36 UTC, egorzalenski commented on app/components/mainAd/components/driversRegistr/styles/driversRegistr.css
> +  margin: 30px 40px 0px 0px;
тоже самое

2018-07-07 10:36 UTC, egorzalenski commented on app/components/newsBlock/index.js
> +Object.keys(Text).forEach(element => {
тоже самое

2018-07-07 10:36 UTC, egorzalenski commented on app/components/newsBlock/styles/newsBlock.css
> +  padding: 40px 14px 0px 14px;
и тут

2018-07-07 10:36 UTC, egorzalenski commented on app/components/uberFooter/components/infoLinks/components/doublingLinks/components/socialLinks/index.js
> +const State = {
и тут

2018-07-07 10:36 UTC, egorzalenski commented on app/components/clientAdv/index.js
>  import React from 'react';
и переименуй все `index.js` в такое же как название папки
чтобы было `/clientAdv/clientAdv.js`
так по проекту удобнее искать

2018-07-07 10:36 UTC, egorzalenski commented on app/components/mainAd/components/driversRegistr/index.js
>                <a id="license-link" href="/">
`id` выноси в `const` перед компонентом

2018-07-10 15:30 UTC, VKNS commented
у

2018-07-10 15:30 UTC, closed without merging